FROM kumatea/tensorflow:2.6.0-py36

RUN apt update && apt install -y --fix-missing libhdf5-serial-dev hdf5-tools libhdf5-dev 

RUN mkdir /models

WORKDIR /app

ARG  CONFIG
ENV CONFIG ${CONFIG}

RUN pip install --upgrade pip

RUN pip install --no-binary=h5py h5py

COPY requirements.txt requirements.txt 
RUN pip install -r requirements.txt 

COPY ./train_model.py .

EXPOSE 5000

CMD [ "python3" , "train_model.py" ]